//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VRodriguezGrupoReformaEntities : DbContext
    {
        public VRodriguezGrupoReformaEntities()
            : base("name=VRodriguezGrupoReformaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleFactura> DetalleFacturas { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
    
        public virtual int AddPersona(string nombre, string direccion, Nullable<int> edad, string correo, string habilidadPrincipal, string habilidadSecundaria)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("Edad", edad) :
                new ObjectParameter("Edad", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var habilidadPrincipalParameter = habilidadPrincipal != null ?
                new ObjectParameter("HabilidadPrincipal", habilidadPrincipal) :
                new ObjectParameter("HabilidadPrincipal", typeof(string));
    
            var habilidadSecundariaParameter = habilidadSecundaria != null ?
                new ObjectParameter("HabilidadSecundaria", habilidadSecundaria) :
                new ObjectParameter("HabilidadSecundaria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPersona", nombreParameter, direccionParameter, edadParameter, correoParameter, habilidadPrincipalParameter, habilidadSecundariaParameter);
        }
    
        public virtual int Funcionalidades(Nullable<int> idPersona, string nombre, string direccion, Nullable<int> edad, string correo, string habilidadPrincipal, string habilidadSecundaria, Nullable<int> idTipo)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("Edad", edad) :
                new ObjectParameter("Edad", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var habilidadPrincipalParameter = habilidadPrincipal != null ?
                new ObjectParameter("HabilidadPrincipal", habilidadPrincipal) :
                new ObjectParameter("HabilidadPrincipal", typeof(string));
    
            var habilidadSecundariaParameter = habilidadSecundaria != null ?
                new ObjectParameter("HabilidadSecundaria", habilidadSecundaria) :
                new ObjectParameter("HabilidadSecundaria", typeof(string));
    
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Funcionalidades", idPersonaParameter, nombreParameter, direccionParameter, edadParameter, correoParameter, habilidadPrincipalParameter, habilidadSecundariaParameter, idTipoParameter);
        }
    }
}
